import type { Category, Location, Ad, User, AuthResponse } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Коровы' },
  { id: 2, name: 'Свиньи' },
  { id: 3, name: 'Овцы' },
  { id: 4, name: 'Козы' },
  { id: 5, name: 'Лошади' },
  { id: 6, name: 'Птица' },
];

export const MOCK_LOCATIONS: Location[] = [
  { id: 1, city: 'Москва', region: 'Московская область' },
  { id: 2, city: 'Санкт-Петербург', region: 'Ленинградская область' },
  { id: 3, city: 'Казань', region: 'Республика Татарстан' },
  { id: 4, city: 'Екатеринбург', region: 'Свердловская область' },
  { id: 5, city: 'Новосибирск', region: 'Новосибирская область' },
];

export const MOCK_CURRENT_USER: User = {
  id: 1,
  fullName: 'Иван Петров',
  phone: '+7 (999) 123-45-67',
  email: 'ivan@example.com',
  createdAt: '2024-01-15T10:00:00',
};

export const MOCK_ADS: Ad[] = [
  {
    id: 1,
    title: 'Молочная корова черно-белой породы',
    description: 'Здоровая молочная корова. Возраст 3 года. Хорошо доится. Отличное здоровье.',
    price: 45000,
    currency: 'RUB',
    status: 'ACTIVE',
    views: [],
    seller: {
      id: 2,
      fullName: 'Петр Сидоров',
      phone: '+7 (995) 111-22-33',
      email: 'petr@example.com',
      createdAt: '2023-06-10T10:00:00',
    },
    category: MOCK_CATEGORIES[0],
    location: MOCK_LOCATIONS[0],
    favoritedBy: [],
    createdAt: '2024-01-20T10:00:00',
    updatedAt: '2024-01-20T10:00:00',
  },
  {
    id: 2,
    title: 'Поросята оптом',
    description: 'Продам поросят от здоровой свиноматки. Возраст 2 месяца. Все привиты.',
    price: 8000,
    currency: 'RUB',
    status: 'ACTIVE',
    views: [],
    seller: {
      id: 3,
      fullName: 'Анна Козлова',
      phone: '+7 (996) 444-55-66',
      email: 'anna@example.com',
      createdAt: '2023-03-20T10:00:00',
    },
    category: MOCK_CATEGORIES[1],
    location: MOCK_LOCATIONS[1],
    favoritedBy: [],
    createdAt: '2024-01-19T10:00:00',
    updatedAt: '2024-01-19T10:00:00',
  },
  {
    id: 3,
    title: 'Овцы мясной породы',
    description: 'Продаю овец мясной породы в возрасте 1.5 года. Вес 60-70 кг. Здоровые, активные.',
    price: 12000,
    currency: 'RUB',
    status: 'ACTIVE',
    views: [],
    seller: {
      id: 4,
      fullName: 'Борис Животновский',
      phone: '+7 (997) 777-88-99',
      email: 'boris@example.com',
      createdAt: '2023-09-05T10:00:00',
    },
    category: MOCK_CATEGORIES[2],
    location: MOCK_LOCATIONS[2],
    favoritedBy: [],
    createdAt: '2024-01-18T10:00:00',
    updatedAt: '2024-01-18T10:00:00',
  },
  {
    id: 4,
    title: 'Козы молочной породы',
    description: 'Огромный выбор коз для молока и мяса. Разные возраста и окраски.',
    price: 18000,
    currency: 'RUB',
    status: 'ACTIVE',
    views: [],
    seller: {
      id: 2,
      fullName: 'Петр Сидоров',
      phone: '+7 (995) 111-22-33',
      email: 'petr@example.com',
      createdAt: '2023-06-10T10:00:00',
    },
    category: MOCK_CATEGORIES[3],
    location: MOCK_LOCATIONS[3],
    favoritedBy: [],
    createdAt: '2024-01-17T10:00:00',
    updatedAt: '2024-01-17T10:00:00',
  },
  {
    id: 5,
    title: 'Рысак верховной лошадь',
    description: 'Красивая лошадь для верховой езды. Возраст 5 лет. Спокойный характер. Отличный во всех дисциплинах.',
    price: 350000,
    currency: 'RUB',
    status: 'ACTIVE',
    views: [],
    seller: {
      id: 5,
      fullName: 'Екатерина Морозова',
      phone: '+7 (994) 666-77-88',
      email: 'ekaterina@example.com',
      createdAt: '2023-04-12T10:00:00',
    },
    category: MOCK_CATEGORIES[4],
    location: MOCK_LOCATIONS[4],
    favoritedBy: [],
    createdAt: '2024-01-16T10:00:00',
    updatedAt: '2024-01-16T10:00:00',
  },
  {
    id: 6,
    title: 'Цыплята бройлеры',
    description: 'Здоровые суточные цыплята бройлеры. Отличная комбикормовка. Гарантия выживаемости 95%.',
    price: 35,
    currency: 'RUB',
    status: 'ACTIVE',
    views: [],
    seller: {
      id: 3,
      fullName: 'Анна Козлова',
      phone: '+7 (996) 444-55-66',
      email: 'anna@example.com',
      createdAt: '2023-03-20T10:00:00',
    },
    category: MOCK_CATEGORIES[5],
    location: MOCK_LOCATIONS[0],
    favoritedBy: [],
    createdAt: '2024-01-15T10:00:00',
    updatedAt: '2024-01-15T10:00:00',
  },
];

export const mockAuthResponse: AuthResponse = {
  token: 'mock-jwt-token-' + Date.now(),
  user: MOCK_CURRENT_USER,
};
